name: ShowOffW
version: 3.0
main: me.crafter.mc.showoffw.ShowOffW
description: >
             Show your item to other players.
commands:
   showoff:
      permission: showoff.showoff
      usage: |
         /showoff
   showto:
      permission: showoff.showto
      usage: |
         /showto <Player>
   i:
      permission: showoff.i
      usage: |
         /i